package com.smarthome.energy.protocol;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Random;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Randomised equivalence check: the hand-built DFA against a reference regular expression.
 *
 * <p>The wire format is a regular language, so it can be written as a regex — which gives a
 * cheap and convincing correctness argument for the transition table. This generates roughly
 * {@link #SAMPLE_COUNT} strings across four populations (well-formed frames, frames with one
 * mutated character, truncations, and random noise over the alphabet the format uses) and
 * asserts that</p>
 *
 * <pre>
 *   validator.accepts(s) == REFERENCE.matcher(s).matches()
 * </pre>
 *
 * <p>for every one. Agreement across that corpus is strong empirical evidence that the
 * automaton recognises exactly the intended language.</p>
 *
 * <p>The mutation and truncation populations matter more than the noise: purely random
 * strings are almost all rejected by both, so they mostly prove that two things agree about
 * garbage. Near-misses are where a transition table is actually wrong, which is why most of
 * the corpus is generated by damaging a valid frame rather than by rolling dice.</p>
 *
 * <p>The seed is fixed so a failure is reproducible; the counters are asserted so that a
 * generator that silently stopped producing valid frames could not pass by testing nothing.</p>
 *
 * <p>Run alone with:</p>
 *
 * <pre>
 *   mvn test -Dtest=WireFormatFuzzTest
 * </pre>
 *
 * @author Anmol Goyal (anmol-goyal7)
 */
class WireFormatFuzzTest {

    /** Strings compared per run. */
    private static final int SAMPLE_COUNT = 100_000;

    /** Fixed so a disagreement can be reproduced exactly. */
    private static final long SEED = 20260729L;

    /**
     * The same language as the DFA, written the other way round. Kept as a literal rather than
     * assembled from {@link MeterMessage}'s constants: a reference that shared its definition
     * with the thing it checks could agree with it while both were wrong.
     */
    private static final Pattern REFERENCE =
            Pattern.compile("RDG\\|D\\d+\\|T\\d+\\|V\\d+\\.\\d+\\|I\\d+\\.\\d+\\|P\\d+\\.\\d+\\n");

    /** The characters a mutation can introduce — mostly ones that are legal somewhere else. */
    private static final char[] ALPHABET =
            "0123456789RDGTVIP|.\n xX?*-,".toCharArray();

    private final WireFormatValidator validator = new WireFormatValidator();

    @Test
    @DisplayName("the DFA and a reference regex agree on ~100k generated strings")
    void agreesWithReferenceRegex() {
        Random random = new Random(SEED);
        int accepted = 0;
        int mutated = 0;
        String firstDisagreement = null;
        int disagreements = 0;

        for (int i = 0; i < SAMPLE_COUNT; i++) {
            String candidate = switch (i % 4) {
                case 0 -> wellFormed(random);
                case 1 -> {
                    mutated++;
                    yield mutate(wellFormed(random), random);
                }
                case 2 -> truncate(wellFormed(random), random);
                default -> noise(random);
            };

            boolean byDfa = validator.accepts(candidate);
            boolean byRegex = REFERENCE.matcher(candidate).matches();
            if (byDfa) {
                accepted++;
            }
            if (byDfa != byRegex) {
                disagreements++;
                if (firstDisagreement == null) {
                    firstDisagreement = "dfa=" + byDfa + " regex=" + byRegex + " for \""
                            + candidate.replace("\n", "\\n") + "\"";
                }
            }
        }

        assertEquals(0, disagreements, "first disagreement: " + firstDisagreement);
        assertTrue(accepted > SAMPLE_COUNT / 8,
                "the corpus should contain plenty of valid frames, but only " + accepted
                        + " of " + SAMPLE_COUNT + " were accepted");
        assertTrue(mutated > 0, "the corpus should contain mutated frames");
    }

    @Test
    @DisplayName("every frame the simulator's formatter produces is accepted")
    void acceptsEverythingTheFormatterProduces() {
        Random random = new Random(SEED);
        for (int i = 0; i < 10_000; i++) {
            String frame = MeterMessage.format(com.smarthome.energy.model.Reading.fromEpochMillis(
                    1 + random.nextInt(999),
                    Math.abs(random.nextLong() % 4_000_000_000_000L),
                    random.nextDouble() * 300,
                    random.nextDouble() * 40,
                    random.nextDouble() * 5_000));
            assertTrue(validator.accepts(frame),
                    "formatter produced a frame the validator rejects: " + frame);
        }
    }

    /** A frame drawn from the shape the meters actually emit. */
    private static String wellFormed(Random random) {
        return "RDG|D" + (1 + random.nextInt(20))
                + "|T" + (1_700_000_000_000L + random.nextInt(1_000_000))
                + "|V" + random.nextInt(300) + "." + pad(random.nextInt(100))
                + "|I" + random.nextInt(40) + "." + pad(random.nextInt(100))
                + "|P" + random.nextInt(5_000) + "." + pad(random.nextInt(100))
                + "\n";
    }

    /** Overwrites one character — the population that finds real transition-table mistakes. */
    private static String mutate(String frame, Random random) {
        int index = random.nextInt(frame.length());
        char replacement = ALPHABET[random.nextInt(ALPHABET.length)];
        return frame.substring(0, index) + replacement + frame.substring(index + 1);
    }

    /** Cuts a frame short, which is what a meter dying mid-write produces. */
    private static String truncate(String frame, Random random) {
        return frame.substring(0, random.nextInt(frame.length() + 1));
    }

    /** Random characters over the format's own alphabet. */
    private static String noise(Random random) {
        int length = random.nextInt(50);
        StringBuilder out = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            out.append(ALPHABET[random.nextInt(ALPHABET.length)]);
        }
        return out.toString();
    }

    private static String pad(int twoDigits) {
        return twoDigits < 10 ? "0" + twoDigits : String.valueOf(twoDigits);
    }
}
